### ISSUE TITLE
Project North Starに関する情報

### ISSUE THREAD

**Issue by supertask** [yutokun/XR-Headset-Comparison#6]
XR-Headset-Comparisonを重宝しているものです．

Project North StarがSmart-Prototyping（アメリカ人が経営している中国の会社）で販売されており，下記リンクを参考情報のリンクに追加していただけると助かります．
https://www.smart-prototyping.com/Project-North-Star-Kit?search=north%20star

価格については，組み立て済みが$499，3Dプリントパーツ込みのキットが$399，3Dプリントパーツを含まないキットが$299です．

**Comment by yutokun** [comment]
いつもご覧になって下さり & 情報ありがとうございます。ご協力いただけて嬉しいです。
連休中に対応させていただきます。

**Comment by yutokun** [comment]
ゆるゆるやっているサイトなのでブランチ切ったりしていませんが、追記させていただきました。ニュアンス違いなどあればおっしゃっていただければと思います。
https://xr-comparison.yutokun.com/?t=north

**Comment by supertask** [comment]
ありがとうございます．
